### ISSUE TITLE
Consider potentially using Python 3 ndb library

### ISSUE THREAD

**Issue by jacobg** [potatolondon/django-gcloud-connectors#5]
I just discovered the following statement:
> Update (11 Apr 2019): According to a talk at the Cloud Next 2019 conference, Google is actively working on a Python 3 ndb library.
https://gaedevs.com/blog/things-to-understand-before-migrating-your-pyt

I'm creating this issue to consider the possibly using this library for this repo. Of course, it's not even available now. But it might be something to keep an eye on, particularly for caching layer.

**Comment by davidwtbuxton** [comment]
It's here: https://github.com/googleapis/python-ndb

**Comment by jacobg** [comment]
Aha! That's great. Hopefully they'll come out with some documentation.

**Comment by jasonmyers** [comment]
Some documentation:  

https://cloud.google.com/appengine/docs/standard/python3/migrating-to-cloud-ndb
https://googleapis.dev/python/python-ndb/latest/index.html

**Comment by Kazade** [comment]
Thanks for the information! 

We won't be using NDB for a number of reasons, but mainly that using the Cloud Datastore API directly already provides us what we need and using NDB would mean we'd be trying to work around their abstraction.

As for caching, I'm interested to see how they've replaced their memcache caching (given that Python 3 has no memcache) but NDB in-memory caching has always had a flaw where fetches would return a reference to an existing object which could result in subtle bugs; Djangae's caching layer doesn't suffer this.

We're trying to arrange for some people-time to push this project forward and complete the connector - hopefully you'll see some movement here soon :)

**Comment by jasonmyers** [comment]
Thanks for the update, we're looking forward to this!  A couple questions if you don't mind:

  1. Is the goal here to be able to run djangae on Django 2.x (PY3) against Appengine Standard 2nd Gen (PY3) via datastore connector?  
(That's what we're trying to be able to do.  We're still using the ABP/djangoappengine fork, but looking for an upgrade path to Py3, but remaining on Django/Appengine Standard)

  1. Since this is now decoupled (?) from djangae, could this also be used in a stock version of Django 2.x to run an app on something other than Appengine Standard (say, Appengine Flexible), but using this connector to still connect to the Appengine Datastore?

**Comment by Kazade** [comment]
Yes and Yes :)

This is being implemented so you'll be able to connect from Cloud Datastore from any Django 2.0 platform.

**Comment by jasonmyers** [comment]
Awesome, thanks!
